import mongoose from "mongoose";

const lineItemSchema = new mongoose.Schema(
    {
        // Description
        description: {
            type: String,
            required: true
        },
        // Charge type
        chargeType: {
            type: String,
            enum: [
                'BASE_MAINTENANCE',
                'WATER_CHARGES',
                'ELECTRICITY',
                'PARKING',
                'CLUB_MEMBERSHIP',
                'SINKING_FUND',
                'REPAIR_FUND',
                'LATE_FEE',
                'ARREARS',
                'OTHER',
            ],
            default: 'OTHER',
        },
        // Quantity
        quantity: {
            type: Number,
            default: 1
        },
        // Unit price
        unitPrice: {
            type: Number,
            required: true
        },
        // Amount
        amount: {
            type: Number,
            required: true
        },
    },
    { _id: false }
);

const invoiceSchema = new mongoose.Schema(
    {
        // Reference to the associated Society
        societyId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Society',
            required: true,
        },
        // Invoice number
        invoiceNumber: {
            type: String,
            required: true,
            unique: true,
            trim: true,
        },
        // Reference to the associated Unit
        unitId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Unit',
            required: true,
        },
        // Reference to the associated Resident
        residentId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Resident',
            required: true,
        },
        // Billing period start
        billingPeriodStart: {
            type: Date,
            required: true
        },
        // Billing period end
        billingPeriodEnd: {
            type: Date,
            required: true
        },
        // Invoice date
        invoiceDate: {
            type: Date,
            required: true
        },
        // Due date
        dueDate: {
            type: Date,
            required: true
        },
        // Line items
        lineItems: {
            type: [lineItemSchema],
            required: true,
            default: []
        },
        // Subtotal
        subtotal: {
            type: Number,
            required: true,
            default: 0
        },
        // Tax amount
        taxAmount: {
            type: Number,
            default: 0
        },
        // Tax percentage
        taxPercentage: {
            type: Number,
            default: 0
        },
        // Discount amount
        discountAmount: {
            type: Number,
            default: 0
        },
        // Discount reason
        discountReason: {
            type: String,
            default: null
        },
        // Late fee applied
        lateFeeApplied: {
            type: Number,
            default: 0
        },
        // Arrears amount
        arrearsAmount: {
            type: Number,
            default: 0
        },
        // Total amount
        totalAmount: {
            type: Number,
            required: true
        },
        // Paid amount
        paidAmount: {
            type: Number,
            default: 0
        },
        // Balance amount
        balanceAmount: {
            type: Number,
            default: 0
        },
        // Status
        status: {
            type: String,
            enum: ['DRAFT', 'SENT', 'PAID', 'PARTIAL', 'OVERDUE', 'CANCELLED', 'WAIVED'],
            default: 'DRAFT',
        },
        // Payment date
        paymentDate: {
            type: Date,
            default: null
        },
        // Pdf url
        pdfUrl: {
            type: String,
            default: null
        },
        // Notes
        notes: {
            type: String,
            default: null
        },
        // Reminders sent
        remindersSent: {
            type: Number,
            default: 0
        },
        // Last reminder at
        lastReminderAt: {
            type: Date,
            default: null
        },
        // Created by
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            default: null,
        },
        // Indicates whether auto generated is true or false
        isAutoGenerated: {
            type: Boolean,
            default: true
        },
        // Reference to the associated Razorpay order
        razorpayOrderId: {
            type: String,
            default: null
        },
    },
    { timestamps: true }
);

invoiceSchema.index({ societyId: 1 });
invoiceSchema.index({ unitId: 1 });
invoiceSchema.index({ residentId: 1 });
invoiceSchema.index({ status: 1 });
invoiceSchema.index({ dueDate: 1 });
invoiceSchema.index({ societyId: 1, status: 1 });

export default mongoose.model('Invoice', invoiceSchema);
